//
//  PermissionModel.swift
//  AllPermissionsImpl
//
//  Created by Deepak Kaligotla on 19/04/24.
//

import Foundation
import SwiftData
import HealthKit

@Model
final class PermissionModel {
    var name: String
    var allowed: Bool
    
    init(name: String, allowed: Bool) {
        self.name = name
        self.allowed = allowed
    }
}

final class MyHealth: Identifiable {
    var healthName: String
    var healthType: HKObjectType
    
    init(healthName: String, healthType: HKObjectType) {
        self.healthName = healthName
        self.healthType = healthType
    }
    
    static var healthList: [MyHealth] = [
        MyHealth(healthName: "Allergy", healthType: HKObjectType.clinicalType(forIdentifier: .allergyRecord)!),
        MyHealth(healthName: "Clinical Note", healthType: HKObjectType.clinicalType(forIdentifier: .clinicalNoteRecord)!),
        MyHealth(healthName: "Condition", healthType: HKObjectType.clinicalType(forIdentifier: .conditionRecord)!),
        MyHealth(healthName: "Coverage", healthType: HKObjectType.clinicalType(forIdentifier: .coverageRecord)!),
        MyHealth(healthName: "Immunization", healthType: HKObjectType.clinicalType(forIdentifier: .immunizationRecord)!),
        MyHealth(healthName: "Lab Result", healthType: HKObjectType.clinicalType(forIdentifier: .labResultRecord)!),
        MyHealth(healthName: "Medication", healthType: HKObjectType.clinicalType(forIdentifier: .medicationRecord)!),
        MyHealth(healthName: "Procedure", healthType: HKObjectType.clinicalType(forIdentifier: .procedureRecord)!),
        MyHealth(healthName: "Vital Sign", healthType: HKObjectType.clinicalType(forIdentifier: .vitalSignRecord)!),
        MyHealth(healthName: "Abdominal Cramps", healthType: HKObjectType.categoryType(forIdentifier: .abdominalCramps)!),
        MyHealth(healthName: "Acne", healthType: HKObjectType.categoryType(forIdentifier: .acne)!),
        MyHealth(healthName: "Appetite Changes", healthType: HKObjectType.categoryType(forIdentifier: .appetiteChanges)!),
        MyHealth(healthName: "Stand Hour", healthType: HKObjectType.categoryType(forIdentifier: .appleStandHour)!),
        MyHealth(healthName: "Walking Steadiness Event", healthType: HKObjectType.categoryType(forIdentifier: .appleWalkingSteadinessEvent)!),
        MyHealth(healthName: "Bladder Incontinence", healthType: HKObjectType.categoryType(forIdentifier: .bladderIncontinence)!),
        MyHealth(healthName: "Bloating", healthType: HKObjectType.categoryType(forIdentifier: .bloating)!),
        MyHealth(healthName: "Breast Pain", healthType: HKObjectType.categoryType(forIdentifier: .breastPain)!),
        MyHealth(healthName: "Cervical Mucus Quality", healthType: HKObjectType.categoryType(forIdentifier: .cervicalMucusQuality)!),
        MyHealth(healthName: "Chest Tightness/Pain", healthType: HKObjectType.categoryType(forIdentifier: .chestTightnessOrPain)!),
        MyHealth(healthName: "Chills", healthType: HKObjectType.categoryType(forIdentifier: .chills)!),
        MyHealth(healthName: "Constipation", healthType: HKObjectType.categoryType(forIdentifier: .constipation)!),
        MyHealth(healthName: "Contraceptive", healthType: HKObjectType.categoryType(forIdentifier: .contraceptive)!),
        MyHealth(healthName: "Coughing", healthType: HKObjectType.categoryType(forIdentifier: .coughing)!),
        MyHealth(healthName: "Diarrhea", healthType: HKObjectType.categoryType(forIdentifier: .diarrhea)!),
        MyHealth(healthName: "Dizziness", healthType: HKObjectType.categoryType(forIdentifier: .dizziness)!),
        MyHealth(healthName: "Dryskin", healthType: HKObjectType.categoryType(forIdentifier: .drySkin)!),
        MyHealth(healthName: "Environmental Audio Exposure", healthType: HKObjectType.categoryType(forIdentifier: .environmentalAudioExposureEvent)!),
        MyHealth(healthName: "Fainting", healthType: HKObjectType.categoryType(forIdentifier: .fainting)!),
        MyHealth(healthName: "Fatigue", healthType: HKObjectType.categoryType(forIdentifier: .fatigue)!),
        MyHealth(healthName: "Fever", healthType: HKObjectType.categoryType(forIdentifier: .fever)!),
        MyHealth(healthName: "Generalized Body Ache", healthType: HKObjectType.categoryType(forIdentifier: .generalizedBodyAche)!),
        MyHealth(healthName: "Hairloss", healthType: HKObjectType.categoryType(forIdentifier: .hairLoss)!),
        MyHealth(healthName: "Handwashing Event", healthType: HKObjectType.categoryType(forIdentifier: .handwashingEvent)!),
        MyHealth(healthName: "Headache", healthType: HKObjectType.categoryType(forIdentifier: .headache)!),
        MyHealth(healthName: "Headphone Audio Exposure", healthType: HKObjectType.categoryType(forIdentifier: .headphoneAudioExposureEvent)!),
        MyHealth(healthName: "Heartburn", healthType: HKObjectType.categoryType(forIdentifier: .heartburn)!),
        MyHealth(healthName: "High Heart Rate", healthType: HKObjectType.categoryType(forIdentifier: .highHeartRateEvent)!),
        MyHealth(healthName: "Hot Flashes", healthType: HKObjectType.categoryType(forIdentifier: .hotFlashes)!),
        MyHealth(healthName: "Infrequent Menstrual Cycles", healthType: HKObjectType.categoryType(forIdentifier: .infrequentMenstrualCycles)!),
        MyHealth(healthName: "Intermenstrual Bleeding", healthType: HKObjectType.categoryType(forIdentifier: .intermenstrualBleeding)!),
        MyHealth(healthName: "Irregualr Heart Rhythm", healthType: HKObjectType.categoryType(forIdentifier: .irregularHeartRhythmEvent)!),
        MyHealth(healthName: "Irregular Menstrual Cycles", healthType: HKObjectType.categoryType(forIdentifier: .irregularMenstrualCycles)!),
        MyHealth(healthName: "Lactation", healthType: HKObjectType.categoryType(forIdentifier: .lactation)!),
        MyHealth(healthName: "Loss of Smell", healthType: HKObjectType.categoryType(forIdentifier: .lossOfSmell)!),
        MyHealth(healthName: "Loss of Taste", healthType: HKObjectType.categoryType(forIdentifier: .lossOfTaste)!),
        MyHealth(healthName: "Low Cardio Fitness", healthType: HKObjectType.categoryType(forIdentifier: .lowCardioFitnessEvent)!),
        MyHealth(healthName: "Low Heart Rate", healthType: HKObjectType.categoryType(forIdentifier: .lowHeartRateEvent)!),
        MyHealth(healthName: "Lower Back Pain", healthType: HKObjectType.categoryType(forIdentifier: .lowerBackPain)!),
        MyHealth(healthName: "Memory Lapse", healthType: HKObjectType.categoryType(forIdentifier: .memoryLapse)!),
        MyHealth(healthName: "Menstrual Flow", healthType: HKObjectType.categoryType(forIdentifier: .menstrualFlow)!),
        MyHealth(healthName: "Mindful Session", healthType: HKObjectType.categoryType(forIdentifier: .mindfulSession)!),
        MyHealth(healthName: "Mood Changes", healthType: HKObjectType.categoryType(forIdentifier: .moodChanges)!),
        MyHealth(healthName: "Nausea", healthType: HKObjectType.categoryType(forIdentifier: .nausea)!),
        MyHealth(healthName: "Night Sweats", healthType: HKObjectType.categoryType(forIdentifier: .nightSweats)!),
        MyHealth(healthName: "Ovulation Test Result", healthType: HKObjectType.categoryType(forIdentifier: .ovulationTestResult)!),
        MyHealth(healthName: "Pelvic Pain", healthType: HKObjectType.categoryType(forIdentifier: .pelvicPain)!),
        MyHealth(healthName: "Persistent Intermenstrual Bleeding", healthType: HKObjectType.categoryType(forIdentifier: .persistentIntermenstrualBleeding)!),
        MyHealth(healthName: "Pregnancy", healthType: HKObjectType.categoryType(forIdentifier: .pregnancy)!),
        MyHealth(healthName: "Pregnancy Test Result", healthType: HKObjectType.categoryType(forIdentifier: .pregnancyTestResult)!),
        MyHealth(healthName: "Progesterone Test Result", healthType: HKObjectType.categoryType(forIdentifier: .progesteroneTestResult)!),
        MyHealth(healthName: "ProLonged Menstrual Periods", healthType: HKObjectType.categoryType(forIdentifier: .prolongedMenstrualPeriods)!),
        MyHealth(healthName: "Rapid Pounding / Fluttering Hearbeat", healthType: HKObjectType.categoryType(forIdentifier: .rapidPoundingOrFlutteringHeartbeat)!),
        MyHealth(healthName: "Runny Nose", healthType: HKObjectType.categoryType(forIdentifier: .runnyNose)!),
        MyHealth(healthName: "Sexual Activity", healthType: HKObjectType.categoryType(forIdentifier: .sexualActivity)!),
        MyHealth(healthName: "Shortness of Breath", healthType: HKObjectType.categoryType(forIdentifier: .shortnessOfBreath)!),
        MyHealth(healthName: "Sinus Congestion", healthType: HKObjectType.categoryType(forIdentifier: .sinusCongestion)!),
        MyHealth(healthName: "Skipped Hearbeat", healthType: HKObjectType.categoryType(forIdentifier: .skippedHeartbeat)!),
        MyHealth(healthName: "Sleep Analysis", healthType: HKObjectType.categoryType(forIdentifier: .sleepAnalysis)!),
        MyHealth(healthName: "Sleep Changes", healthType: HKObjectType.categoryType(forIdentifier: .sleepChanges)!),
        MyHealth(healthName: "Sore Throat", healthType: HKObjectType.categoryType(forIdentifier: .soreThroat)!),
        MyHealth(healthName: "Tooth Brushing Event", healthType: HKObjectType.categoryType(forIdentifier: .toothbrushingEvent)!),
        MyHealth(healthName: "Vignal Dryness", healthType: HKObjectType.categoryType(forIdentifier: .vaginalDryness)!),
        MyHealth(healthName: "Vomiting", healthType: HKObjectType.categoryType(forIdentifier: .vomiting)!),
        MyHealth(healthName: "Wheezing", healthType: HKObjectType.categoryType(forIdentifier: .wheezing)!),
        MyHealth(healthName: "Active Energy Burning", healthType: HKObjectType.quantityType(forIdentifier: .activeEnergyBurned)!),
        MyHealth(healthName: "Exerciese Time", healthType: HKObjectType.quantityType(forIdentifier: .appleExerciseTime)!),
        MyHealth(healthName: "Move Time", healthType: HKObjectType.quantityType(forIdentifier: .appleMoveTime)!),
        MyHealth(healthName: "Sleeping Wrist Temperature", healthType: HKObjectType.quantityType(forIdentifier: .appleSleepingWristTemperature)!),
        MyHealth(healthName: "Stand Time", healthType: HKObjectType.quantityType(forIdentifier: .appleStandTime)!),
        MyHealth(healthName: "Walking Steadiness", healthType: HKObjectType.quantityType(forIdentifier: .appleWalkingSteadiness)!),
        MyHealth(healthName: "Atrial Fibrillation Burden", healthType: HKObjectType.quantityType(forIdentifier: .atrialFibrillationBurden)!),
        MyHealth(healthName: "Basal Body Temperature", healthType: HKObjectType.quantityType(forIdentifier: .basalBodyTemperature)!),
        MyHealth(healthName: "Basal Enery Burned", healthType: HKObjectType.quantityType(forIdentifier: .basalEnergyBurned)!),
        MyHealth(healthName: "Blood Alchohol Content", healthType: HKObjectType.quantityType(forIdentifier: .bloodAlcoholContent)!),
        MyHealth(healthName: "Blood Glucose", healthType: HKObjectType.quantityType(forIdentifier: .bloodGlucose)!),
        MyHealth(healthName: "Blood Pressure Diastolic", healthType: HKObjectType.quantityType(forIdentifier: .bloodPressureDiastolic)!),
        MyHealth(healthName: "Blood Pressure Systolic", healthType: HKObjectType.quantityType(forIdentifier: .bloodPressureSystolic)!),
        MyHealth(healthName: "Body Fat %", healthType: HKObjectType.quantityType(forIdentifier: .bodyFatPercentage)!),
        MyHealth(healthName: "Body Mass", healthType: HKObjectType.quantityType(forIdentifier: .bodyMass)!),
        MyHealth(healthName: "Body Mass Index", healthType: HKObjectType.quantityType(forIdentifier: .bodyMassIndex)!),
        MyHealth(healthName: "Body temperature", healthType: HKObjectType.quantityType(forIdentifier: .bodyTemperature)!),
        MyHealth(healthName: "Cycling Cadence", healthType: HKObjectType.quantityType(forIdentifier: .cyclingCadence)!),
        MyHealth(healthName: "Cycling Functional threshold Power", healthType: HKObjectType.quantityType(forIdentifier: .cyclingFunctionalThresholdPower)!),
        MyHealth(healthName: "Cycling Power", healthType: HKObjectType.quantityType(forIdentifier: .cyclingPower)!),
        MyHealth(healthName: "Cycling Speed", healthType: HKObjectType.quantityType(forIdentifier: .cyclingSpeed)!),
        MyHealth(healthName: "Dietary Biotin", healthType: HKObjectType.quantityType(forIdentifier: .dietaryBiotin)!),
        MyHealth(healthName: "Dietary Caffeine", healthType: HKObjectType.quantityType(forIdentifier: .dietaryCaffeine)!),
        MyHealth(healthName: "Dietary Calcium", healthType: HKObjectType.quantityType(forIdentifier: .dietaryCalcium)!),
        MyHealth(healthName: "Dietary Carbohydrates", healthType: HKObjectType.quantityType(forIdentifier: .dietaryCarbohydrates)!),
        MyHealth(healthName: "Dietary Chloride", healthType: HKObjectType.quantityType(forIdentifier: .dietaryChloride)!),
        MyHealth(healthName: "Dietary Cholesterol", healthType: HKObjectType.quantityType(forIdentifier: .dietaryCholesterol)!),
        MyHealth(healthName: "Dietary Chromium", healthType: HKObjectType.quantityType(forIdentifier: .dietaryChromium)!),
        MyHealth(healthName: "Dietary Copper", healthType: HKObjectType.quantityType(forIdentifier: .dietaryCopper)!),
        MyHealth(healthName: "Dietary Energy Consumed", healthType: HKObjectType.quantityType(forIdentifier: .dietaryEnergyConsumed)!),
        MyHealth(healthName: "Dietary Fat Monounsaturated", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFatMonounsaturated)!),
        MyHealth(healthName: "Dietary Fat Polyunsaturated", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFatPolyunsaturated)!),
        MyHealth(healthName: "Dietary Fat Saturated", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFatSaturated)!),
        MyHealth(healthName: "Dietary Fat Total", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFatTotal)!),
        MyHealth(healthName: "Dietary Fiber", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFiber)!),
        MyHealth(healthName: "Dietary Folate", healthType: HKObjectType.quantityType(forIdentifier: .dietaryFolate)!),
        MyHealth(healthName: "Dietary Iodine", healthType: HKObjectType.quantityType(forIdentifier: .dietaryIodine)!),
        MyHealth(healthName: "Dietary Iron", healthType: HKObjectType.quantityType(forIdentifier: .dietaryIron)!),
        MyHealth(healthName: "Dietary Magnesium", healthType: HKObjectType.quantityType(forIdentifier: .dietaryMagnesium)!),
        MyHealth(healthName: "Dietary Manganese", healthType: HKObjectType.quantityType(forIdentifier: .dietaryManganese)!),
        MyHealth(healthName: "Dietary Molybdenum", healthType: HKObjectType.quantityType(forIdentifier: .dietaryMolybdenum)!),
        MyHealth(healthName: "Dietary Niacin", healthType: HKObjectType.quantityType(forIdentifier: .dietaryNiacin)!),
        MyHealth(healthName: "Dietary Pantothenic Acid", healthType: HKObjectType.quantityType(forIdentifier: .dietaryPantothenicAcid)!),
        MyHealth(healthName: "Dietary Phosphorus", healthType: HKObjectType.quantityType(forIdentifier: .dietaryPhosphorus)!),
        MyHealth(healthName: "Dietary Potassiuium", healthType: HKObjectType.quantityType(forIdentifier: .dietaryPotassium)!),
        MyHealth(healthName: "Dietary Protein", healthType: HKObjectType.quantityType(forIdentifier: .dietaryProtein)!),
        MyHealth(healthName: "Dietary Riboflavin", healthType: HKObjectType.quantityType(forIdentifier: .dietaryRiboflavin)!),
        MyHealth(healthName: "Dietary Selenium", healthType: HKObjectType.quantityType(forIdentifier: .dietarySelenium)!),
        MyHealth(healthName: "Dietary Sodium", healthType: HKObjectType.quantityType(forIdentifier: .dietarySodium)!),
        MyHealth(healthName: "Dietary Sugar", healthType: HKObjectType.quantityType(forIdentifier: .dietarySugar)!),
        MyHealth(healthName: "Dietary Thiamin", healthType: HKObjectType.quantityType(forIdentifier: .dietaryThiamin)!),
        MyHealth(healthName: "Dietary VitaminA", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminA)!),
        MyHealth(healthName: "Dietary VitaminB12", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminB12)!),
        MyHealth(healthName: "Dietary VitaminB6", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminB6)!),
        MyHealth(healthName: "Dietary VitaminC", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminC)!),
        MyHealth(healthName: "Dietary VitaminD", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminD)!),
        MyHealth(healthName: "Dietary VitaminE", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminE)!),
        MyHealth(healthName: "Dietary VitaminK", healthType: HKObjectType.quantityType(forIdentifier: .dietaryVitaminK)!),
        MyHealth(healthName: "Dietary Water", healthType: HKObjectType.quantityType(forIdentifier: .dietaryWater)!),
        MyHealth(healthName: "Dietary Zinc,", healthType: HKObjectType.quantityType(forIdentifier: .dietaryZinc)!),
        MyHealth(healthName: "Distance Cycling", healthType: HKObjectType.quantityType(forIdentifier: .distanceCycling)!),
        MyHealth(healthName: "Distance Downhill Snow Sports", healthType: HKObjectType.quantityType(forIdentifier: .distanceDownhillSnowSports)!),
        MyHealth(healthName: "Distance Swimming", healthType: HKObjectType.quantityType(forIdentifier: .distanceSwimming)!),
        MyHealth(healthName: "Distance Walking Running", healthType: HKObjectType.quantityType(forIdentifier: .distanceWalkingRunning)!),
        MyHealth(healthName: "Distance Wheelchair", healthType: HKObjectType.quantityType(forIdentifier: .distanceWheelchair)!),
        MyHealth(healthName: "Electrodermal Activity", healthType: HKObjectType.quantityType(forIdentifier: .electrodermalActivity)!),
        MyHealth(healthName: "Environmental Audio Exposure", healthType: HKObjectType.quantityType(forIdentifier: .environmentalAudioExposure)!),
        MyHealth(healthName: "Environmental Sound Reduction", healthType: HKObjectType.quantityType(forIdentifier: .environmentalSoundReduction)!),
        MyHealth(healthName: "Flights Climbed", healthType: HKObjectType.quantityType(forIdentifier: .flightsClimbed)!),
        MyHealth(healthName: "Forced Expiratory Volume1", healthType: HKObjectType.quantityType(forIdentifier: .forcedExpiratoryVolume1)!),
        MyHealth(healthName: "ForcedVital Capacity", healthType: HKObjectType.quantityType(forIdentifier: .forcedVitalCapacity)!),
        MyHealth(healthName: "Headphone Audio Exposure", healthType: HKObjectType.quantityType(forIdentifier: .headphoneAudioExposure)!),
        MyHealth(healthName: "Heart Rate", healthType: HKObjectType.quantityType(forIdentifier: .heartRate)!),
        MyHealth(healthName: "Heart Rate Recovery One Minute", healthType: HKObjectType.quantityType(forIdentifier: .heartRateRecoveryOneMinute)!),
        MyHealth(healthName: "Heart Rate Variability SDNN", healthType: HKObjectType.quantityType(forIdentifier: .heartRateVariabilitySDNN)!),
        MyHealth(healthName: "Height", healthType: HKObjectType.quantityType(forIdentifier: .height)!),
        MyHealth(healthName: "Inhaler Usage", healthType: HKObjectType.quantityType(forIdentifier: .inhalerUsage)!),
        MyHealth(healthName: "Insulin Delivery", healthType: HKObjectType.quantityType(forIdentifier: .insulinDelivery)!),
        MyHealth(healthName: "LeanBody Mass", healthType: HKObjectType.quantityType(forIdentifier: .leanBodyMass)!),
        MyHealth(healthName: "Nike Fuel", healthType: HKObjectType.quantityType(forIdentifier: .nikeFuel)!),
        MyHealth(healthName: "Number Of Alcoholic Beverages", healthType: HKObjectType.quantityType(forIdentifier: .numberOfAlcoholicBeverages)!),
        MyHealth(healthName: "Number Of Times Fallen", healthType: HKObjectType.quantityType(forIdentifier: .numberOfTimesFallen)!),
        MyHealth(healthName: "Oxygen Saturation", healthType: HKObjectType.quantityType(forIdentifier: .oxygenSaturation)!),
        MyHealth(healthName: "Peak Expiratory FlowRate", healthType: HKObjectType.quantityType(forIdentifier: .peakExpiratoryFlowRate)!),
        MyHealth(healthName: "Peripheral Perfusion Index", healthType: HKObjectType.quantityType(forIdentifier: .peripheralPerfusionIndex)!),
        MyHealth(healthName: "Physical Effort", healthType: HKObjectType.quantityType(forIdentifier: .physicalEffort)!),
        MyHealth(healthName: "Push Count", healthType: HKObjectType.quantityType(forIdentifier: .pushCount)!),
        MyHealth(healthName: "Respiratory Rate", healthType: HKObjectType.quantityType(forIdentifier: .respiratoryRate)!),
        MyHealth(healthName: "Resting Heart Rate", healthType: HKObjectType.quantityType(forIdentifier: .restingHeartRate)!),
        MyHealth(healthName: "Running Ground Contact Time", healthType: HKObjectType.quantityType(forIdentifier: .runningGroundContactTime)!),
        MyHealth(healthName: "Running Power", healthType: HKObjectType.quantityType(forIdentifier: .runningPower)!),
        MyHealth(healthName: "Running Speed", healthType: HKObjectType.quantityType(forIdentifier: .runningSpeed)!),
        MyHealth(healthName: "Running Stride Length", healthType: HKObjectType.quantityType(forIdentifier: .runningStrideLength)!),
        MyHealth(healthName: "Running Vertical Oscillation", healthType: HKObjectType.quantityType(forIdentifier: .runningVerticalOscillation)!),
        MyHealth(healthName: "Six Minute Walk Test Distance", healthType: HKObjectType.quantityType(forIdentifier: .sixMinuteWalkTestDistance)!),
        MyHealth(healthName: "Stair Ascent Speed", healthType: HKObjectType.quantityType(forIdentifier: .stairAscentSpeed)!),
        MyHealth(healthName: "Stair Descent Speed", healthType: HKObjectType.quantityType(forIdentifier: .stairDescentSpeed)!),
        MyHealth(healthName: "Step Count", healthType: HKObjectType.quantityType(forIdentifier: .stepCount)!),
        MyHealth(healthName: "Swimming Stroke Count", healthType: HKObjectType.quantityType(forIdentifier: .swimmingStrokeCount)!),
        MyHealth(healthName: "Time In Daylight", healthType: HKObjectType.quantityType(forIdentifier: .timeInDaylight)!),
        MyHealth(healthName: "Underwater Depth", healthType: HKObjectType.quantityType(forIdentifier: .underwaterDepth)!),
        MyHealth(healthName: "UV Exposure", healthType: HKObjectType.quantityType(forIdentifier: .uvExposure)!),
        MyHealth(healthName: "VO2 Max", healthType: HKObjectType.quantityType(forIdentifier: .vo2Max)!),
        MyHealth(healthName: "Waist Circumference", healthType: HKObjectType.quantityType(forIdentifier: .waistCircumference)!),
        MyHealth(healthName: "Walking Asymmetry Percentage", healthType: HKObjectType.quantityType(forIdentifier: .walkingAsymmetryPercentage)!),
        MyHealth(healthName: "Walking Double Support Percentage", healthType: HKObjectType.quantityType(forIdentifier: .walkingDoubleSupportPercentage)!),
        MyHealth(healthName: "Walking HeartRate Average", healthType: HKObjectType.quantityType(forIdentifier: .walkingHeartRateAverage)!),
        MyHealth(healthName: "Walking Speed", healthType: HKObjectType.quantityType(forIdentifier: .walkingSpeed)!),
        MyHealth(healthName: "Walking StepLength", healthType: HKObjectType.quantityType(forIdentifier: .walkingStepLength)!),
        MyHealth(healthName: "Water Temperature", healthType: HKObjectType.quantityType(forIdentifier: .waterTemperature)!),
        MyHealth(healthName: "Activity Summary Type", healthType: HKObjectType.activitySummaryType()),
        MyHealth(healthName: "Workout Type", healthType: HKObjectType.workoutType()),
        MyHealth(healthName: "Heartbeat Series", healthType: HKSeriesType.heartbeat())
    ]
    
    static var healthTypes: Set<HKObjectType> {
        Set(healthList.map { $0.healthType })
    }
}
