# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OMS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OMS
  pod 'Alamofire', '~> 5.0'
  pod 'AlamofireImage', '~> 4.1'
end
