source 'https://github.com/brightcove/BrightcoveSpecs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Shinchan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shinchan
  pod 'Brightcove-Player-Core/XCFramework'

  target 'ShinchanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShinchanUITests' do
    # Pods for testing
  end

end
